from CNNClassifier.components.data_ingestion import DataIngestion
from CNNClassifier.components.prepare_base_model import PrepareBaseModel
from CNNClassifier.components.prepare_callback import PrepareCallback
from CNNClassifier.components.training import Training
from CNNClassifier.components.evaluation import Evaluation